# Generated by Django 4.0.4 on 2022-05-23 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('product_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('product_receive_by', models.CharField(blank=True, max_length=255, null=True)),
                ('product_issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('product_issue_by', models.CharField(blank=True, max_length=255, null=True)),
                ('product_issue_to', models.CharField(blank=True, max_length=255, null=True)),
                ('product_created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('product_reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('product_last_updated', models.DateTimeField(auto_now=True)),
                ('product_export_to_csv', models.BooleanField(default=False)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
