# Generated by Django 4.0.4 on 2022-05-23 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product_export_to_csv',
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
