# Generated by Django 4.0.4 on 2022-05-25 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_stock_product_receive_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('product_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('product_receive_by', models.CharField(blank=True, max_length=255, null=True)),
                ('product_receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('product_issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('product_issue_by', models.CharField(blank=True, max_length=255, null=True)),
                ('product_issue_to', models.CharField(blank=True, max_length=255, null=True)),
                ('product_created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('product_reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('product_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('product_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('product_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
